# Generated by Django 3.0.8 on 2020-08-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('short_text', models.CharField(max_length=300, verbose_name='Описание')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='Изображение')),
            ],
        ),
    ]
