# Generated by Django 3.0.8 on 2020-08-04 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file',
        ),
    ]
