# Generated by Django 3.0.8 on 2020-08-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_news_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='short_text',
        ),
        migrations.AddField(
            model_name='news',
            name='author_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='news',
            name='author_uri',
            field=models.URLField(null=True, verbose_name='Ссылка автора'),
        ),
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание статьи'),
        ),
    ]
