# Generated by Django 3.0.8 on 2020-08-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200806_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.CharField(max_length=100, null=True, verbose_name='Дата'),
        ),
    ]
