# Generated by Django 3.0.8 on 2020-08-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200806_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Дата'),
        ),
    ]
