# Generated by Django 3.0.8 on 2020-08-31 13:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200827_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='text',
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 31, 13, 26, 34, 436225, tzinfo=utc), null=True, verbose_name='Дата публикации'),
        ),
    ]
