# Generated by Django 3.0.8 on 2020-09-02 18:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200901_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 2, 18, 29, 43, 24918, tzinfo=utc), null=True, verbose_name='Дата публикации'),
        ),
    ]
