# Generated by Django 3.0.8 on 2020-09-07 12:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200902_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='news',
            name='author_uri',
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(max_length=100, null=True, verbose_name='Сайт-автор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 7, 12, 24, 16, 629438, tzinfo=utc), null=True, verbose_name='Дата публикации'),
        ),
    ]
